# Generated by Django 4.1.5 on 2023-02-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
    ]
